[supervisord]
nodaemon=true

[program:redis]
command=/usr/bin/redis-server --protected-mode no --bind 0.0.0.0
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:spring]
command=java -Xmx256m -Xss512k -jar /app/app.jar
autostart=true
autorestart=true
priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
